# generated by datamodel-codegen:
#   filename:  0.DOIP_Op.ListOperations-Response.json
#   timestamp: 2024-09-16T08:00:23+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Extra, Field


class Status(Enum):
    field_0_DOIP_Status_001 = '0.DOIP/Status.001'
    field_0_DOIP_Status_101 = '0.DOIP/Status.101'
    field_0_DOIP_Status_102 = '0.DOIP/Status.102'
    field_0_DOIP_Status_103 = '0.DOIP/Status.103'
    field_0_DOIP_Status_104 = '0.DOIP/Status.104'
    field_0_DOIP_Status_105 = '0.DOIP/Status.105'
    field_0_DOIP_Status_200 = '0.DOIP/Status.200'
    field_0_DOIP_Status_500 = '0.DOIP/Status.500'


class ListOperations(BaseModel):
    class Config:
        extra = Extra.forbid

    requestId: Optional[str] = Field(
        None,
        description='requestId: the identifier of the request to which this is a response. The DOIP service must include in its response the requestId provided by the client.',
    )
    status: Status = Field(
        ...,
        description='status: an identifier that indicates the status of the request. Status codes shall have associated unique identifiers resolvable as specified in the IRP.',
    )
    output: List[str] = Field(
        ...,
        description='a serialized list of strings based on the default serialization, each of which is an operation id that the target DO supports.',
    )
