# generated by datamodel-codegen:
#   filename:  0.DOIP_Op.Update-Response.json
#   version:   0.26.0

from __future__ import annotations

from typing import Any, Dict, Literal, Optional

from pydantic import BaseModel, Extra, Field


class Elements(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(
        ..., description='id: identifier of the element; must be unique within a DO.'
    )
    length: Optional[str] = Field(None, description='length of the data portion.')
    type: str = Field(
        ...,
        description='requestId: the identifier of the request provided by the client; shall be unique within a given DOIP session so clients can distinguish between DOIP service responses. The requestId shall be a string not exceeding 4096 bits.',
    )
    attributes: Optional[Dict[str, Any]] = Field(
        None,
        description='one or more fields serialized as an object using the default serialization, or as a JSON (sub) object.',
    )


class DoipDoSerialization(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str = Field(..., description='id: the identifier of the DO.')
    type: str = Field(
        ...,
        description='type: the DO type. Must be 0.TYPE/DO or its extension. See Types section.',
    )
    attributes: Optional[Dict[str, Any]] = Field(
        None,
        description='attributes: one or more fields (key-value pairs) serialized as a JSON (sub) object.',
    )
    elements: Optional[Elements] = Field(
        None,
        description='description: one or more elements serialized as an array in the default serialization, with each element consisting of',
    )
    signatures: Optional[str] = Field(
        None,
        description='Required for DOs of type 0.TYPE/DOIPServiceInfo and 0.TYPE/DOIPOperation; otherwise optional. The field is an array of strings in the default serialization; each string is in JWS format19 with an unencoded detached payload.',
    )


class UpdateResponse(BaseModel):
    class Config:
        extra = Extra.forbid

    requestId: Optional[str] = Field(
        None,
        description='requestId: the identifier of the request to which this is a response. The DOIP service must include in its response the requestId provided by the client.',
    )
    status: Literal['0.DOIP/Status.001'] = Field(
        ...,
        description='status: an identifier that indicates the status of the request. Status codes shall have associated unique identifiers resolvable as specified in the IRP.',
    )
    output: DoipDoSerialization = Field(
        ..., description='serialization of a digital object'
    )
